### PR TITLE
Message users (with role) and store response in database

### PR DESCRIPTION
**Pull request by SamWinterhalder**
The bot needs to be able to message all members who have the role specified in `config.json`. To do this the bot needs to have `Intents.member = True` so that the bot can see the members in the guild. It will message these members with the 
the custom messages which are also set in `config.json`.

It should then store this response, along with other responses to subsequent questions, in the databse.

To message each person and store each reponse, the flow is as follows:
1. Task: Send first message to members with role (end task)
2. Bot receives message from user in DM
3. Bot checks to see if it is expecting a message from user
4. If the reply was expected then log to database (and send next message if exists)

### CODE REVIEW

**Comment by SamWinterhalder** [comment]
Bot now also creates the database but does not store messages in it yet

**Comment by SamWinterhalder** [comment]
@jamesgeddes Do you think it would be better to move the database creation to another file (which is called from `main.py` when the bot is started?

Obviously this breaks up the code quite a bit.

**Comment by jamesgeddes** [comment]
Sounds reasonable to do the database operations in `db.py` or similar

**Comment by SamWinterhalder** [comment]
There are a couple options for asking a user multiple questions:
- Create a separate task for each message to be sent
    - most likely be more readable
    - be easier
    - this would allow more customisation of times and content?
- have all messages being asked from the same task
    - this would probably be less readable
    - may make the config a bit nicer

Shall think about this when it isn't half 3 in the morning (it is probably quite obvious which is better 😄)

**Comment by jamesgeddes** [comment]
[Coffee](https://amzn.to/38HyVf2) is your friend :laughing:

**Comment by jamesgeddes** [comment]
Joking aside, which option would lead to less hard coding? Feels like if you have a task per question then that would lead to those questions being hard coded rather than passed to the function.

**Comment by SamWinterhalder** [comment]
Well, currently the messages are being taken directly from 'config.json' and I see no reason for that to change, whether that is in separate tasks or not.

The only thing that I think could get a bit messy is the changing of intervals/starting of each loop as they might have to be defined explicitly. This is something that I guess will just have to be found out when I get round to it.

Hopefully have some time later when I get back from ER.

**Comment by SamWinterhalder** [comment]
Upon reflection I think that it would be better to have the messages being sent from the same task. 

It appears that it will be more readable this way (because there is no need to have multiple `before_loop()` functions/more complex scheduling for working out when to start each loop).

I am however curious whether this approach will work with messaging multiple users. I am not sure whether the bot will wait for user 1 to reply to all messages before messaging user 2. This will obviously not be acceptable so will need to use multiple tasks or consider other options.

**Comment by SamWinterhalder** [comment]
> I am not sure whether the bot will wait for user 1 to reply to all messages before messaging user 2.

This does appear to be the case using the method that I was wanting to implement.

The next thing that I am wanting to try (still using a single task) could be more database dependant and goes as follows:
1. Task: Send first message to members with role (end task)
2. Bot receives message from user in DM
3. Bot checks to see if it is expecting a message from user.  
4. If the reply was expected then log to database (and send next message if exists) <br><br>

Checking whether the bot is expecting a reply from a user can be done by either:
- looking in the database and checking messages exchanged for succes criteria
- looking at the DM history and checking recent messages for success criteria

This approach could mean that the amount  of questions to ask is more dynamic - defined in config.

**Comment by SamWinterhalder** [comment]
@jamesgeddes I think this is almost ready - I just need to maybe make some functions for some of the SQL and minor stuff.
Take a look and see what ya think

**Review by jamesgeddes — APPROVED** [review]

**Comment by jamesgeddes** [comment]
LGTM mate :smile:

**Pull request merged**
