### PR TITLE
Migrate to Python

### PR DESCRIPTION
**Pull request by SamWinterhalder**
My main two reasons for choosing JS over Python when starting was being able to continue learning JS, which I am less familliar with, and as it seems to have more documentation / libraries which are of use.

Upon starting I have now decided that I do not like JavaScript in any capacity and I feel there is enough support and libraries for Python which I can utilize.

### CODE REVIEW

**Comment by SamWinterhalder** [comment]
todo: create schedule command

**Comment by jamesgeddes** [comment]
Not sure if it is what you are looking for but the Python [schedule](https://pypi.org/project/schedule/) library is pretty good

**Comment by SamWinterhalder** [comment]
I am trying to work out if I can do it with discord.ext.tasks or if I should just use schedule

**Comment by SamWinterhalder** [comment]
config.json

```
...
"msg1": {
    "start": "YYYY-MM-DD HH:MM:SS",
    "interval": "HH:MM:SS",
    "message": "This is the message to send."
},
```

**Comment by SamWinterhalder** [comment]
@jamesgeddes Eager to hear your thoughts on how to structure the config file - mostly the start and interval.

**Review by jamesgeddes — APPROVED** [review]

**Comment by jamesgeddes** [comment]
LGTM. I guess you'll want to change the interval to something a bit longer later but that's fine for now.

**Comment by SamWinterhalder** [comment]
Yeh, I was more wondering about how to lay out the config file, specifically how to format the interval and start time.

Is `"YYYY-MM-DD HH:MM:SS"` good for start time and `"HH:MM:SS"` good for interval between executions?

**Comment by jamesgeddes** [comment]
Yep, sounds good

**Pull request merged**
